name: "🐞 Report a problem"
description: "Report an issue with validate-express-req-body"
title: "[🐞 BUG]:"
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Environment
      description: |
        Please provide details about your environment:
      value: |
        Node version: 
        npm version: 
        package version:
    validations:
     required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Please include sample code and rules that caused the issue:
      value: |
        1. Sample code.
        2. Applied rules.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        Describe what you expected to happen. Markdown is supported.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: |
        Describe what actually happened, including any error messages from the console.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue.
          required: false

  - type: textarea
    attributes:
      label: Additional Comments
      description: |
        Is there anything else you'd like the team to know?
