# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI release

on:
  workflow_dispatch:

permissions: 
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - run: npm ci
    - run: npm run build
  
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [build]
    steps: 
    - uses: actions/checkout@v2
    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - run: npm ci
    - run: npm run semantic-release
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
