name: CI build and release

on:
  workflow_dispatch:

permissions: 
  contents: write
  issues: write
  pull-requests: write

jobs:
  quality:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [20]
        # os: [ubuntu-latest, windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - run: npm ci
    - run: npm run build
    # - run: npm test
  
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [quality]
    steps: 
    - uses: actions/checkout@v2
    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - run: npm ci
    - run: npm run semantic-release
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
